import './globals.scss';
import type { Metadata } from 'next';
import Navbar from './components/Navbar';
import { ChakraProvider } from '@chakra-ui/react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"nature roboto"}>
        <ChakraProvider>
          <Navbar></Navbar>
          {children}
        </ChakraProvider>
      </body>
    </html >
  );
}
